# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for hammerhead configurations
Name: jolla-configuration-hammerhead
Requires:
- pattern:jolla-hw-adaptation-hammerhead
- pattern:jolla-configuration-sfe
# Pre-installed applications, since we don't support OTA well enough:
- sailfish-office
- jolla-calculator
- jolla-email
- jolla-notes
- jolla-clock
- jolla-mediaplayer
- jolla-calendar
- sailfish-weather
Summary: Jolla Configuration hammerhead

